// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package profileproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetProfileRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type UpdateProfileRequest struct {
	Header               *RequestHeader              `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Field                *UpdateProfileRequest_Field `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UpdateProfileRequest) Reset()         { *m = UpdateProfileRequest{} }
func (m *UpdateProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileRequest) ProtoMessage()    {}
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *UpdateProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileRequest.Unmarshal(m, b)
}
func (m *UpdateProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileRequest.Merge(m, src)
}
func (m *UpdateProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileRequest.Size(m)
}
func (m *UpdateProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileRequest proto.InternalMessageInfo

func (m *UpdateProfileRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateProfileRequest) GetField() *UpdateProfileRequest_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

type UpdateProfileRequest_Field struct {
	FirstName                    string   `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	MiddleName                   string   `protobuf:"bytes,2,opt,name=MiddleName,proto3" json:"MiddleName,omitempty"`
	LastName                     string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	ContactEmail                 string   `protobuf:"bytes,4,opt,name=ContactEmail,proto3" json:"ContactEmail,omitempty"`
	ContactMobile                string   `protobuf:"bytes,5,opt,name=ContactMobile,proto3" json:"ContactMobile,omitempty"`
	ContactPhone                 string   `protobuf:"bytes,6,opt,name=ContactPhone,proto3" json:"ContactPhone,omitempty"`
	AddressStreet                string   `protobuf:"bytes,7,opt,name=AddressStreet,proto3" json:"AddressStreet,omitempty"`
	AddressCity                  string   `protobuf:"bytes,8,opt,name=AddressCity,proto3" json:"AddressCity,omitempty"`
	AddressPostCode              string   `protobuf:"bytes,9,opt,name=AddressPostCode,proto3" json:"AddressPostCode,omitempty"`
	AddressState                 string   `protobuf:"bytes,10,opt,name=AddressState,proto3" json:"AddressState,omitempty"`
	AddressCountry               string   `protobuf:"bytes,11,opt,name=AddressCountry,proto3" json:"AddressCountry,omitempty"`
	EmergencyContactFullName     string   `protobuf:"bytes,12,opt,name=EmergencyContactFullName,proto3" json:"EmergencyContactFullName,omitempty"`
	EmergencyContactRelationship string   `protobuf:"bytes,13,opt,name=EmergencyContactRelationship,proto3" json:"EmergencyContactRelationship,omitempty"`
	EmergencyContactMobile       string   `protobuf:"bytes,14,opt,name=EmergencyContactMobile,proto3" json:"EmergencyContactMobile,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *UpdateProfileRequest_Field) Reset()         { *m = UpdateProfileRequest_Field{} }
func (m *UpdateProfileRequest_Field) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileRequest_Field) ProtoMessage()    {}
func (*UpdateProfileRequest_Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2, 0}
}

func (m *UpdateProfileRequest_Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileRequest_Field.Unmarshal(m, b)
}
func (m *UpdateProfileRequest_Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileRequest_Field.Marshal(b, m, deterministic)
}
func (m *UpdateProfileRequest_Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileRequest_Field.Merge(m, src)
}
func (m *UpdateProfileRequest_Field) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileRequest_Field.Size(m)
}
func (m *UpdateProfileRequest_Field) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileRequest_Field.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileRequest_Field proto.InternalMessageInfo

func (m *UpdateProfileRequest_Field) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetContactMobile() string {
	if m != nil {
		return m.ContactMobile
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetAddressStreet() string {
	if m != nil {
		return m.AddressStreet
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetAddressCity() string {
	if m != nil {
		return m.AddressCity
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetAddressPostCode() string {
	if m != nil {
		return m.AddressPostCode
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetAddressState() string {
	if m != nil {
		return m.AddressState
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetAddressCountry() string {
	if m != nil {
		return m.AddressCountry
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetEmergencyContactFullName() string {
	if m != nil {
		return m.EmergencyContactFullName
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetEmergencyContactRelationship() string {
	if m != nil {
		return m.EmergencyContactRelationship
	}
	return ""
}

func (m *UpdateProfileRequest_Field) GetEmergencyContactMobile() string {
	if m != nil {
		return m.EmergencyContactMobile
	}
	return ""
}

type ProfileResponse struct {
	StatusCode           int32                 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ProfileResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ProfileResponse) GetData() *ProfileResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProfileResponse_Data struct {
	Avatar                       string   `protobuf:"bytes,1,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Username                     string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	FirstName                    string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	MiddleName                   string   `protobuf:"bytes,4,opt,name=MiddleName,proto3" json:"MiddleName,omitempty"`
	LastName                     string   `protobuf:"bytes,5,opt,name=LastName,proto3" json:"LastName,omitempty"`
	ContactEmail                 string   `protobuf:"bytes,6,opt,name=ContactEmail,proto3" json:"ContactEmail,omitempty"`
	ContactMobile                string   `protobuf:"bytes,7,opt,name=ContactMobile,proto3" json:"ContactMobile,omitempty"`
	ContactPhone                 string   `protobuf:"bytes,8,opt,name=ContactPhone,proto3" json:"ContactPhone,omitempty"`
	AddressStreet                string   `protobuf:"bytes,9,opt,name=AddressStreet,proto3" json:"AddressStreet,omitempty"`
	AddressCity                  string   `protobuf:"bytes,10,opt,name=AddressCity,proto3" json:"AddressCity,omitempty"`
	AddressPostCode              string   `protobuf:"bytes,11,opt,name=AddressPostCode,proto3" json:"AddressPostCode,omitempty"`
	AddressState                 string   `protobuf:"bytes,12,opt,name=AddressState,proto3" json:"AddressState,omitempty"`
	AddressCountry               string   `protobuf:"bytes,13,opt,name=AddressCountry,proto3" json:"AddressCountry,omitempty"`
	EmployeeTittle               string   `protobuf:"bytes,14,opt,name=EmployeeTittle,proto3" json:"EmployeeTittle,omitempty"`
	EmployeeRole                 string   `protobuf:"bytes,15,opt,name=EmployeeRole,proto3" json:"EmployeeRole,omitempty"`
	Warehouses                   []string `protobuf:"bytes,16,rep,name=Warehouses,proto3" json:"Warehouses,omitempty"`
	EmergencyContactFullName     string   `protobuf:"bytes,17,opt,name=EmergencyContactFullName,proto3" json:"EmergencyContactFullName,omitempty"`
	EmergencyContactRelationship string   `protobuf:"bytes,18,opt,name=EmergencyContactRelationship,proto3" json:"EmergencyContactRelationship,omitempty"`
	EmergencyContactMobile       string   `protobuf:"bytes,19,opt,name=EmergencyContactMobile,proto3" json:"EmergencyContactMobile,omitempty"`
	Supervisor                   string   `protobuf:"bytes,20,opt,name=Supervisor,proto3" json:"Supervisor,omitempty"`
	HiredDate                    string   `protobuf:"bytes,21,opt,name=HiredDate,proto3" json:"HiredDate,omitempty"`
	Timezone                     string   `protobuf:"bytes,22,opt,name=Timezone,proto3" json:"Timezone,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *ProfileResponse_Data) Reset()         { *m = ProfileResponse_Data{} }
func (m *ProfileResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse_Data) ProtoMessage()    {}
func (*ProfileResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3, 0}
}

func (m *ProfileResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse_Data.Unmarshal(m, b)
}
func (m *ProfileResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse_Data.Marshal(b, m, deterministic)
}
func (m *ProfileResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse_Data.Merge(m, src)
}
func (m *ProfileResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse_Data.Size(m)
}
func (m *ProfileResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse_Data proto.InternalMessageInfo

func (m *ProfileResponse_Data) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ProfileResponse_Data) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProfileResponse_Data) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileResponse_Data) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *ProfileResponse_Data) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ProfileResponse_Data) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *ProfileResponse_Data) GetContactMobile() string {
	if m != nil {
		return m.ContactMobile
	}
	return ""
}

func (m *ProfileResponse_Data) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *ProfileResponse_Data) GetAddressStreet() string {
	if m != nil {
		return m.AddressStreet
	}
	return ""
}

func (m *ProfileResponse_Data) GetAddressCity() string {
	if m != nil {
		return m.AddressCity
	}
	return ""
}

func (m *ProfileResponse_Data) GetAddressPostCode() string {
	if m != nil {
		return m.AddressPostCode
	}
	return ""
}

func (m *ProfileResponse_Data) GetAddressState() string {
	if m != nil {
		return m.AddressState
	}
	return ""
}

func (m *ProfileResponse_Data) GetAddressCountry() string {
	if m != nil {
		return m.AddressCountry
	}
	return ""
}

func (m *ProfileResponse_Data) GetEmployeeTittle() string {
	if m != nil {
		return m.EmployeeTittle
	}
	return ""
}

func (m *ProfileResponse_Data) GetEmployeeRole() string {
	if m != nil {
		return m.EmployeeRole
	}
	return ""
}

func (m *ProfileResponse_Data) GetWarehouses() []string {
	if m != nil {
		return m.Warehouses
	}
	return nil
}

func (m *ProfileResponse_Data) GetEmergencyContactFullName() string {
	if m != nil {
		return m.EmergencyContactFullName
	}
	return ""
}

func (m *ProfileResponse_Data) GetEmergencyContactRelationship() string {
	if m != nil {
		return m.EmergencyContactRelationship
	}
	return ""
}

func (m *ProfileResponse_Data) GetEmergencyContactMobile() string {
	if m != nil {
		return m.EmergencyContactMobile
	}
	return ""
}

func (m *ProfileResponse_Data) GetSupervisor() string {
	if m != nil {
		return m.Supervisor
	}
	return ""
}

func (m *ProfileResponse_Data) GetHiredDate() string {
	if m != nil {
		return m.HiredDate
	}
	return ""
}

func (m *ProfileResponse_Data) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "profileproto.RequestHeader")
	proto.RegisterType((*GetProfileRequest)(nil), "profileproto.GetProfileRequest")
	proto.RegisterType((*UpdateProfileRequest)(nil), "profileproto.UpdateProfileRequest")
	proto.RegisterType((*UpdateProfileRequest_Field)(nil), "profileproto.UpdateProfileRequest.Field")
	proto.RegisterType((*ProfileResponse)(nil), "profileproto.ProfileResponse")
	proto.RegisterType((*ProfileResponse_Data)(nil), "profileproto.ProfileResponse.Data")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4d, 0x4f, 0xdb, 0x4e,
	0x10, 0xc6, 0x05, 0xc4, 0x09, 0x99, 0xbc, 0xf0, 0x67, 0xff, 0x14, 0xad, 0x52, 0xda, 0x22, 0xab,
	0x45, 0x9c, 0x72, 0x00, 0x89, 0x43, 0x0f, 0x95, 0x28, 0xaf, 0x87, 0x52, 0x45, 0x06, 0xda, 0xf3,
	0x82, 0x07, 0xb2, 0xaa, 0xe3, 0x75, 0x77, 0x37, 0x48, 0xe9, 0xd7, 0xea, 0xbd, 0xa7, 0xf6, 0x13,
	0xf4, 0x0b, 0x55, 0xbb, 0xde, 0x24, 0xb6, 0x0b, 0xc6, 0x12, 0x3d, 0xce, 0x6f, 0x66, 0x9e, 0x8d,
	0xb3, 0xcf, 0xa3, 0x85, 0x8e, 0x42, 0x79, 0xc7, 0xaf, 0xb1, 0x9f, 0x48, 0xa1, 0x05, 0x69, 0x27,
	0x52, 0xdc, 0xf0, 0x08, 0x6d, 0xe5, 0xbf, 0x81, 0x4e, 0x80, 0x5f, 0xc7, 0xa8, 0xf4, 0x29, 0xb2,
	0x10, 0x25, 0x59, 0x03, 0x4f, 0x8b, 0x2f, 0x18, 0xd3, 0x85, 0xcd, 0x85, 0xed, 0x66, 0x90, 0x16,
	0xfe, 0x29, 0xac, 0x9e, 0xa0, 0x1e, 0xa4, 0x9b, 0x6e, 0x81, 0xec, 0x42, 0x7d, 0x68, 0x97, 0xec,
	0x6c, 0x6b, 0xe7, 0x79, 0x3f, 0x2b, 0xdd, 0xcf, 0xe9, 0x06, 0x6e, 0xd4, 0xff, 0xed, 0xc1, 0xda,
	0x65, 0x12, 0x32, 0x8d, 0xff, 0x40, 0x8d, 0xbc, 0x03, 0xef, 0x86, 0x63, 0x14, 0xd2, 0x45, 0xbb,
	0xb3, 0x9d, 0xdf, 0xb9, 0xef, 0x9c, 0xfe, 0xb1, 0x99, 0x0f, 0xd2, 0xb5, 0xde, 0xaf, 0x1a, 0x78,
	0x16, 0x90, 0x0d, 0x68, 0x1e, 0x73, 0xa9, 0xf4, 0x47, 0x36, 0x42, 0xf7, 0xed, 0x73, 0x40, 0x5e,
	0x02, 0x9c, 0xf1, 0x30, 0x8c, 0xd0, 0xb6, 0x17, 0x6d, 0x3b, 0x43, 0x48, 0x0f, 0x96, 0x3f, 0x30,
	0xb7, 0xbc, 0x64, 0xbb, 0xb3, 0x9a, 0xf8, 0xd0, 0x3e, 0x10, 0xb1, 0x66, 0xd7, 0xfa, 0x68, 0xc4,
	0x78, 0x44, 0x6b, 0xb6, 0x9f, 0x63, 0xe4, 0x35, 0x74, 0x5c, 0x7d, 0x26, 0xae, 0x78, 0x84, 0xd4,
	0xb3, 0x43, 0x79, 0x98, 0x51, 0x1a, 0x0c, 0x45, 0x8c, 0xb4, 0x9e, 0x53, 0xb2, 0xcc, 0x28, 0xed,
	0x87, 0xa1, 0x44, 0xa5, 0xce, 0xb5, 0x44, 0xd4, 0xb4, 0x91, 0x2a, 0xe5, 0x20, 0xd9, 0x84, 0x96,
	0x03, 0x07, 0x5c, 0x4f, 0xe8, 0xb2, 0x9d, 0xc9, 0x22, 0xb2, 0x0d, 0x2b, 0xae, 0x1c, 0x08, 0xa5,
	0x0f, 0x44, 0x88, 0xb4, 0x69, 0xa7, 0x8a, 0xd8, 0xfc, 0xaa, 0x99, 0x38, 0xd3, 0x48, 0x21, 0xfd,
	0x55, 0x59, 0x46, 0xb6, 0xa0, 0x3b, 0x15, 0x17, 0xe3, 0x58, 0xcb, 0x09, 0x6d, 0xd9, 0xa9, 0x02,
	0x25, 0x6f, 0x81, 0x1e, 0x8d, 0x50, 0xde, 0x62, 0x7c, 0x3d, 0x71, 0x9f, 0x75, 0x3c, 0x8e, 0x22,
	0xfb, 0xbf, 0xb6, 0xed, 0xc6, 0x83, 0x7d, 0xf2, 0x1e, 0x36, 0x8a, 0xbd, 0x00, 0x23, 0xa6, 0xb9,
	0x88, 0xd5, 0x90, 0x27, 0xb4, 0x63, 0xf7, 0x4b, 0x67, 0xc8, 0x1e, 0xac, 0x17, 0xfb, 0xee, 0x42,
	0xba, 0x76, 0xfb, 0x81, 0xae, 0xff, 0xb3, 0x01, 0x2b, 0x33, 0x9f, 0xa9, 0x44, 0xc4, 0xca, 0x7a,
	0x46, 0x69, 0xa6, 0xc7, 0xca, 0xfe, 0x79, 0xc6, 0x52, 0x5e, 0x90, 0x21, 0x84, 0x42, 0x63, 0x84,
	0x4a, 0xb1, 0xdb, 0xa9, 0xa1, 0xa6, 0x25, 0xd9, 0x83, 0x5a, 0xc8, 0x34, 0xb3, 0x4e, 0x6a, 0xed,
	0xf8, 0x79, 0x53, 0x17, 0x8e, 0xe9, 0x1f, 0x32, 0xcd, 0x02, 0x3b, 0xdf, 0xfb, 0x51, 0x87, 0x9a,
	0x29, 0xc9, 0x3a, 0xd4, 0xf7, 0xef, 0x98, 0x66, 0xd2, 0x39, 0xd9, 0x55, 0xc6, 0xa6, 0x97, 0x0a,
	0x65, 0x3c, 0x37, 0xf1, 0xac, 0xce, 0x07, 0x60, 0xa9, 0x3c, 0x00, 0xb5, 0xd2, 0x00, 0x78, 0x8f,
	0x04, 0xa0, 0x5e, 0x25, 0x00, 0x8d, 0x2a, 0x01, 0x58, 0xae, 0x12, 0x80, 0x66, 0x85, 0x00, 0x40,
	0xa5, 0x00, 0xb4, 0xaa, 0x05, 0xa0, 0x5d, 0x29, 0x00, 0x9d, 0x7b, 0x03, 0xb0, 0x05, 0xdd, 0xa3,
	0x51, 0x12, 0x89, 0x09, 0xe2, 0x05, 0xd7, 0x7a, 0x66, 0xbc, 0x02, 0x35, 0x67, 0x4e, 0x49, 0x20,
	0x22, 0xa4, 0x2b, 0xe9, 0x99, 0x59, 0x66, 0xee, 0xec, 0x33, 0x93, 0x38, 0x14, 0x63, 0x85, 0x8a,
	0xfe, 0xb7, 0xb9, 0x64, 0xee, 0x6c, 0x4e, 0x4a, 0xc3, 0xb6, 0xfa, 0xc4, 0xb0, 0x91, 0x27, 0x85,
	0xed, 0xff, 0xb2, 0xb0, 0x99, 0xef, 0x3a, 0x1f, 0x27, 0xe6, 0x51, 0x53, 0x42, 0xd2, 0xb5, 0xd4,
	0x8b, 0x73, 0x62, 0x9c, 0x7c, 0xca, 0x25, 0x86, 0x87, 0xe6, 0x32, 0x9e, 0xa5, 0x4e, 0x9e, 0x01,
	0xe3, 0xd4, 0x0b, 0x3e, 0xc2, 0x6f, 0xc6, 0x3f, 0xeb, 0xa9, 0x53, 0xa7, 0xf5, 0xce, 0xf7, 0x05,
	0x68, 0xb8, 0x7c, 0x91, 0x01, 0x74, 0x4f, 0x50, 0x9b, 0x78, 0x4c, 0xc9, 0xab, 0x7c, 0x10, 0xff,
	0x7a, 0x10, 0x7b, 0x2f, 0x4a, 0x93, 0x4a, 0x3e, 0xc1, 0x6a, 0xfa, 0x22, 0x65, 0x45, 0xfd, 0xc7,
	0x9f, 0xac, 0x47, 0x74, 0xaf, 0xea, 0x16, 0xef, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x95, 0x27,
	0x1f, 0x7e, 0xe9, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileClient is the client API for Profile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileClient interface {
	GetUserProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	UpdateUserProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type profileClient struct {
	cc *grpc.ClientConn
}

func NewProfileClient(cc *grpc.ClientConn) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) GetUserProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/profileproto.Profile/GetUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateUserProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/profileproto.Profile/UpdateUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServer is the server API for Profile service.
type ProfileServer interface {
	GetUserProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error)
	UpdateUserProfile(context.Context, *UpdateProfileRequest) (*ProfileResponse, error)
}

// UnimplementedProfileServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServer struct {
}

func (*UnimplementedProfileServer) GetUserProfile(ctx context.Context, req *GetProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (*UnimplementedProfileServer) UpdateUserProfile(ctx context.Context, req *UpdateProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserProfile not implemented")
}

func RegisterProfileServer(s *grpc.Server, srv ProfileServer) {
	s.RegisterService(&_Profile_serviceDesc, srv)
}

func _Profile_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profileproto.Profile/GetUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetUserProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profileproto.Profile/UpdateUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateUserProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profileproto.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserProfile",
			Handler:    _Profile_GetUserProfile_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _Profile_UpdateUserProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
